[package]
name = "super-wasm"
version = "0.1.0"
authors = ["Elian Gutierrez <eliangu3600103@gmail.com>"]
edition = "2018"

[dependencies]
stdweb = "0.4.2"
yew = { git = "https://github.com/DenisKolodin/yew", features = ["toml", "yaml", "msgpack", "cbor"] }

